### ISSUE TITLE
Issues with use of ellipsis (...) in FastAPI based service (Python 3.8)

### ISSUE THREAD

**Issue by mike-hart** [numirias/semshi#55]
Although I appreciate Semshi isn't yet tested for 3.8, I'd been using 3.8 for a few of the new features and figured I'd try it out. Sadly I ended up with a traceback.

From the FastAPI documentation - https://fastapi.tiangolo.com/tutorial/query-params-str-validations/#make-it-required :
```python
from fastapi import FastAPI, Query

app = FastAPI()


@app.get("/items/")
async def read_items(q: str = Query(..., min_length=3)):
    results = {"items": [{"item_id": "Foo"}, {"item_id": "Bar"}]}
    if q:
        results.update({"q": q})
    return results
```

Trying to enable Semshi on this causes a traceback:
```
Error invoking '.../numirias/semshi/rplugin/python3/semshi:command:Semshi' on channel 9 (python3-rplugin-host):
error caught in request handler '.../numirias/semshi/rplugin/python3/semshi:command:Semshi [['enable']]':
Traceback (most recent call last):
  File ".../numirias/semshi/rplugin/python3/semshi/plugin.py", line 139, in cmd_semshi
    func(self, *args[1:])
  File ".../numirias/semshi/rplugin/python3/semshi/plugin.py", line 38, in wrapper
    func(self, *args, **kwargs)
  File ".../numirias/semshi/rplugin/python3/semshi/plugin.py", line 151, in enable
    self.highlight()
  File ".../numirias/semshi/rplugin/python3/semshi/plugin.py", line 38, in wrapper
    func(self, *args, **kwargs)
  File ".../numirias/semshi/rplugin/python3/semshi/plugin.py", line 171, in highlight
    self._cur_handler.update(force=True, sync=True)
  File ".../numirias/semshi/rplugin/python3/semshi/handler.py", line 67, in update
    self._update_step(force=force, sync=True)
  File ".../numirias/semshi/rplugin/python3/semshi/util.py", line 19, in wrapper
    res = func(*args, **kwargs)
  File ".../numirias/semshi/rplugin/python3/semshi/handler.py", line 159, in _update_step
    add, rem = self._parser.parse(code, force)
  File ".../numirias/semshi/rplugin/python3/semshi/util.py", line 19, in wrapper
    res = func(*args, **kwargs)
  File ".../numirias/semshi/rplugin/python3/semshi/parser.py", line 47, in parse
    return self._parse(*args, **kwargs)
  File ".../numirias/semshi/rplugin/python3/semshi/parser.py", line 68, in _parse
    new_nodes = self._make_nodes(code, new_lines, change_lineno)
  File ".../numirias/semshi/rplugin/python3/semshi/parser.py", line 108, in _make_nodes
    return visitor(lines, symtable_root, ast_root)
  File ".../numirias/semshi/rplugin/python3/semshi/util.py", line 19, in wrapper
    res = func(*args, **kwargs)
  File ".../numirias/semshi/rplugin/python3/semshi/visitor.py", line 46, in visitor
    visitor.visit(ast_root)
  File ".../numirias/semshi/rplugin/python3/semshi/visitor.py", line 122, in visit
    self._iter_node(node)
  File ".../numirias/semshi/rplugin/python3/semshi/visitor.py", line 397, in _iter_node
    self.visit(item)
  File ".../numirias/semshi/rplugin/python3/semshi/visitor.py", line 91, in visit
    self._visit_arg_defaults(node)
  File ".../numirias/semshi/rplugin/python3/semshi/visitor.py", line 150, in _visit_arg_defaults
    self.visit(arg_)
  File ".../numirias/semshi/rplugin/python3/semshi/visitor.py", line 127, in visit
    self._iter_node(node)
  File ".../numirias/semshi/rplugin/python3/semshi/visitor.py", line 397, in _iter_node
    self.visit(item)
  File ".../numirias/semshi/rplugin/python3/semshi/visitor.py", line 127, in visit
    self._iter_node(node)
  File ".../numirias/semshi/rplugin/python3/semshi/visitor.py", line 401, in _iter_node
    self.visit(value)
  File ".../numirias/semshi/rplugin/python3/semshi/visitor.py", line 127, in visit
    self._iter_node(node)
  File ".../numirias/semshi/rplugin/python3/semshi/visitor.py", line 388, in _iter_node
    for field in node._fields:
AttributeError: 'ellipsis' object has no attribute '_fields'
```

I'm running semshi at commit b50f1bcc48bb944704c586b462a5e9d5cdf0d532, neovim 0.5.0, and Python 3.8.0

This appears to work on 3.7.4.

**Comment by numirias** [comment]
Duplicate of #57 
@mike-hart Do you mind checking if the latest update works for you?

**Comment by mike-hart** [comment]
Latest update looks to be working just fine, thanks 👍
